name: tasks_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  uuid: ^4.5.1
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: CabinetGrotesk
      fonts:
        - asset: assets/fonts/CabinetGrotesk-Regular.otf
        - asset: assets/fonts/CabinetGrotesk-Medium.otf
          weight: 500
        - asset: assets/fonts/CabinetGrotesk-Bold.otf
          weight: 700
        - asset: assets/fonts/CabinetGrotesk-Light.otf
          weight: 300
        - asset: assets/fonts/CabinetGrotesk-Extrabold.otf
          weight: 800
        - asset: assets/fonts/CabinetGrotesk-Black.otf
          weight: 900
        - asset: assets/fonts/CabinetGrotesk-Extralight.otf
          weight: 200
        - asset: assets/fonts/CabinetGrotesk-Thin.otf
          weight: 100

