name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [android, ios]
        include:
          - platform: android
            runs-on: ubuntu-latest
          - platform: ios
            runs-on: macos-latest

    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        if: matrix.platform == 'android'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'  # Updated to match SDK requirements
          channel: 'stable'
          cache: true

      - name: Override Dart SDK constraints
        run: |
          sed -i.bak 's/sdk: \^3.5.3/sdk: ">=3.0.0 <4.0.0"/' pubspec.yaml

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android
        if: matrix.platform == 'android'
        run: |
          flutter build apk --release
          flutter build appbundle --release

      - name: Build iOS
        if: matrix.platform == 'ios'
        run: flutter build ios --release --no-codesign

      - name: Upload Android APK
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Android Bundle
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v3
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload iOS Build
        if: matrix.platform == 'ios'
        uses: actions/upload-artifact@v3
        with:
          name: release-ios
          path: build/ios/iphoneos

  create_release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-apk/app-release.apk
            release-bundle/app-release.aab
            release-ios/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 